### PR TITLE
Update to latest DPF and enable automated builds

### PR DESCRIPTION
**Pull request by falkTX**
Hi there!

In the process of getting an updated DPF working well, I am now trying to get some plugins built with the updated version.
I noticed a few peculiarities on the way your makefiles were setup and corrected them.
Additionally, I enabled automated builds for all possible targets that GitHub actions can provide for us (so this is linux x64, armhf, arm64; macOS universal x64+arm64; win32 and win64)

Let me know if something is unclear, hope this is useful to get more people enjoying DragonFly Reverb plugins, I really like these :)

### CODE REVIEW

**Comment by falkTX** [comment]
Just noticed there are many open tickets regarding platform support.
from macOS builds, to arm linux builds, to windows...
all handled in this PR now :)

It is worth also checking win/mac bugs against the updated DPF.
I know at least the issue of plugin close messing with host GL context to be fixed on macOS now.

**Comment by falkTX** [comment]
FYI before you merge if you want to checkout the build artifacts/binaries, the github forked project link provides those.
https://github.com/DISTRHO/dragonfly-reverb/actions/runs/1044689060

**Comment by michaelwillis** [comment]
Thanks, @falkTX! Can you point me to some hints about how to promote the build artifacts to an official release?

I see that the automated build is working for all platforms, but I am now unable to do the build locally on a Mac.

I used to just run `make` and it would work, but now it does this:

```
dragonfly-reverb % make
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C dpf/dgl opengl
make[1]: *** No rule to make target `opengl'.  Stop.
make: *** [dgl] Error 2
```

I see the `Fix up Xcode` step in the macos-universal build, please explain what that does.

For what it's worth, the build works on my Linux machine without incident, and I'm very glad that I never have to manually cross-compile for Windows ever again.

**Comment by falkTX** [comment]
You are missing submodules, nothing else. Build should just work as-is.
The Xcode fixup is for macos-10.15 GitHub image, not something you should or need to do on your own system ever.
(The GitHub image has a broken Xcode installation basically, the 12.4 Xcode doesnt support arm64 while 12.3 does)

Promoting these files to releases is not something I have done yet.
We can look into how sfizz does it https://github.com/sfztools/sfizz/blob/1.0.0/.github/workflows/build.yml#L414

Should I make a new PR for this?

**Comment by michaelwillis** [comment]
@falkTX Thanks! Yes, I was missing a submodule on the mac, it's working now. Incidentally, I used to get lots of compiler warnings about deprecated OpenGL calls. I thought that Apple was planning on stopping support for OpenGL, but now the compiler warnings are gone. Also, I used to jump through hoops getting the plugins to run on MacOS Catalina, but now they work without any trouble.

If you are willing to contribute more work to promoting artifacts to official releases, that would be fantastic, but don't feel like you have to do it... I know you have a lot of different things you are working on. If you don't do it, I can probably figure it out... one of these days...

**Comment by falkTX** [comment]
It is fine, I want to have this for my own plugins as well, so eventually I have to figure it out too.
Unless you are pressed on time for a release, just wait it out and you will see a PR about it eventually.

**Comment by michaelwillis** [comment]
@falkTX :bowtie::thumbsup: Fair enough. I'm in no hurry to make another release, I'm actually trying to spend more time actually making music these days. Maybe I'll implement the bypass feature as we are discussing in the other thread, and then make a release, but I'll wait for your PR.

**Comment by falkTX** [comment]
oh and on macOS support. Apple is still getting rid of OpenGL eventually yeah, I just silence those warnings now because they were too annoying.
I am glad things are working better :)

When Apple does remove OpenGL, we can worry, but for now just keep on going with it.
nanovg has different backends, and DPF (due to pugl) officially supports cairo for rendering now (plus vulkan, but I didnt patch that part on DPF side yet, that stuff is way over my head).
Worst case, we can just go full cairo, that will work regardless of what Apple does.

**Comment by michaelwillis** [comment]
> Worst case, we can just go full cairo, that will work regardless of what Apple does.

Oh, for some reason I thought Cairo was a layer of abstraction that used OpenGL behind the curtain (Kind of like JACK and ALSA)... but I didn't really dig in much to verify that idea. Any word on DPF support for AU or VST3? I was following the AU development a while back, but I'm not aware of what happened to that.

**Comment by falkTX** [comment]
AU is hard to justify, only a couple of hosts support it and only on macOS.
VST3 work has begun, but nothing to see just yet. Mostly delayed because I am doing a fully custom reimplementation of the spec in C (hardcode yes haha) but so that we can skip over the dual-license situation. So final binaries wont be "VST3 plugins" per se, but will be VST3 compatible.

**Pull request merged**
