### PR TITLE
Use Github Actions to build plugins automatically

### PR DESCRIPTION
**Pull request by fayaaz**
WIP: Windows cross compilation not quite working yet

### CODE REVIEW

**Comment by michaelwillis** [comment]
This looks pretty good. I have been compiling the Linux flavor against an older distro. if I remember right, some people reported having glibc compatibility issues when I used the latest Ubuntu, so I used an older one to resolve that.

**Comment by fayaaz** [comment]
Was the older version of Ubuntu 16.04?
The Mac build on Big Sur seemed to run ok, but would have no way of knowing if the plugins actually worked.

**Comment by michaelwillis** [comment]
A few years ago I was building on Ubuntu 14.04, but I don't think there is any reason to go that far back anymore. Using 16.04 is probably plenty good enough.

**Comment by michaelwillis** [comment]
@fayaaz Your original comment says that the Windows build wasn't working yet, any progress on that?

**Comment by michaelwillis** [comment]
@fayaaz Oh, also I should let you know that I'm working on an experimental complete rewrite of this project on a different branch. It is written using a different framework and is completely not backward compatible. I'm kind of chasing a dream about what I want Dragonfly Reverb to be now that I've learned more about DSP and plugin development, but I'm also considering whether Dragonfly Reverb 3.x should continue to have development and bug fixes for people that still want to use it.

**Comment by fayaaz** [comment]
Looking at the v4 branch the build looks doable. The github plays would need to be updated for it.

Regarding Windows, I'm trying to cross compile on Linux on Github Actions. Maybe it's easier to use the Windows runner Github provides? How would I build the plugin on windows?

**Comment by michaelwillis** [comment]
I'm sorry, I don't know of any way to directly build this on Windows. I only have MacOS and Linux available on my machines, and I'm kind of amazed that the cross-compile works at all. Seems like last time I tried the cross compile in a more recent Linux Distro, the name of the wine binaries had changed, but I don't quite remember.

**Comment by falkTX** [comment]
I handle this now in #106 with all possible build types we can get out of github.

**Pull request closed without merging**
