### PR TITLE
Update DPF and CI builds; Fixes and LTO optimization

### PR DESCRIPTION
**Pull request by falkTX**
Hi again, here comes a big one :)

Listing the changes, in no particular order:
1. Update to latest DPF develop branch
2. Small adjustments to work better with latest DPF
3. Remove an unused file
4. Fixes on UI code usage (`DistrhoUI.hpp` is different per-plugin, so we cant share it across builds, a symlink works fine here)
5. LTO is enabled on the CI builds (using the new optional `make WITH_LTO=true` in DPF) which should show small performance improvements
6. JACK always enabled, because it builds and works on all platforms, and why not
7. VST3 also enabled, it is still experimental but already works in most cases (please send any bug reports about it)

### CODE REVIEW

**Comment by falkTX** [comment]
Oh, I updated the CI builds to use Ubuntu 20.04, as with Ubuntu 18.04 we needed ugly hacks in order to cross-build ARM stuff.
And soon enough 20.04 will be 2 years old

**Comment by michaelwillis** [comment]
Thanks @falkTX! I'm going to do some additional work on the CI stuff to get if I can promote the resulting artifacts to downloadable releases.

**Comment by falkTX** [comment]
Cool, I will be on watch for that :)

On a different topic, we should make the UI scalable to high-dpi at some point, DPF already provides such APIs (`getScaleFactor()` on UI side).
I implemented it on my plugins and works well, besides the bitmap based stuff ending up blurred.
Can help you set that up later if you want.

**Comment by michaelwillis** [comment]
> DPF already provides such APIs (`getScaleFactor()` on UI side).

Oh nice. I might try replacing the raster images with new higher detailed ones, and then scale down for low DPI instead of scaling up for high DPI.

**Comment by gitterdude** [comment]
It's a bit sad to see the build fail in Ubuntu 18.04 with commit 886880
18.04 is in Standard Support mode for another year, after all.

Maybe 20.04 could be the lowest supported ARM version, while still having a working x86/64 18.04?

**Comment by falkTX** [comment]
Having different setups for 18.04 and 20.04 complicates things.
But this is quite easy to build yourself anyway, just some barebones dependencies and a "make" command.

**Comment by gitterdude** [comment]
I've built it myself since forever, but the build process bugs out on commit 886880.

But I figured out that the bug is in the symlinks to common/AbstractUI.hpp/cpp in the plugin subfolders.
Replacing ../../common/AbstractUI.hpp with #include "../../common/AbstractUI.hpp" , and the same for the cpp files, solved the build problem.

**Comment by gitterdude** [comment]
```
diff --git a/plugins/dragonfly-early-reflections/AbstractUI.cpp b/plugins/dragonfly-early-reflections/AbstractUI.cpp
index 07adce6..0f0960c 120000
--- a/plugins/dragonfly-early-reflections/AbstractUI.cpp
+++ b/plugins/dragonfly-early-reflections/AbstractUI.cpp
@@ -1 +1 @@
-../../common/AbstractUI.cpp
\ No newline at end of file
+#include "../../common/AbstractUI.cpp"
\ No newline at end of file
diff --git a/plugins/dragonfly-early-reflections/AbstractUI.hpp b/plugins/dragonfly-early-reflections/AbstractUI.hpp
index 39ad25a..806e283 120000
--- a/plugins/dragonfly-early-reflections/AbstractUI.hpp
+++ b/plugins/dragonfly-early-reflections/AbstractUI.hpp
@@ -1 +1 @@
-../../common/AbstractUI.hpp
\ No newline at end of file
+#include "../../common/AbstractUI.hpp"
\ No newline at end of file
diff --git a/plugins/dragonfly-hall-reverb/AbstractUI.cpp b/plugins/dragonfly-hall-reverb/AbstractUI.cpp
index 07adce6..0f0960c 120000
--- a/plugins/dragonfly-hall-reverb/AbstractUI.cpp
+++ b/plugins/dragonfly-hall-reverb/AbstractUI.cpp
@@ -1 +1 @@
-../../common/AbstractUI.cpp
\ No newline at end of file
+#include "../../common/AbstractUI.cpp"
\ No newline at end of file
diff --git a/plugins/dragonfly-hall-reverb/AbstractUI.hpp b/plugins/dragonfly-hall-reverb/AbstractUI.hpp
index 39ad25a..806e283 120000
--- a/plugins/dragonfly-hall-reverb/AbstractUI.hpp
+++ b/plugins/dragonfly-hall-reverb/AbstractUI.hpp
@@ -1 +1 @@
-../../common/AbstractUI.hpp
\ No newline at end of file
+#include "../../common/AbstractUI.hpp"
\ No newline at end of file
diff --git a/plugins/dragonfly-plate-reverb/AbstractUI.cpp b/plugins/dragonfly-plate-reverb/AbstractUI.cpp
index 07adce6..0f0960c 120000
--- a/plugins/dragonfly-plate-reverb/AbstractUI.cpp
+++ b/plugins/dragonfly-plate-reverb/AbstractUI.cpp
@@ -1 +1 @@
-../../common/AbstractUI.cpp
\ No newline at end of file
+#include "../../common/AbstractUI.cpp"
\ No newline at end of file
diff --git a/plugins/dragonfly-plate-reverb/AbstractUI.hpp b/plugins/dragonfly-plate-reverb/AbstractUI.hpp
index 39ad25a..806e283 120000
--- a/plugins/dragonfly-plate-reverb/AbstractUI.hpp
+++ b/plugins/dragonfly-plate-reverb/AbstractUI.hpp
@@ -1 +1 @@
-../../common/AbstractUI.hpp
\ No newline at end of file
+#include "../../common/AbstractUI.hpp"
\ No newline at end of file
diff --git a/plugins/dragonfly-room-reverb/AbstractUI.cpp b/plugins/dragonfly-room-reverb/AbstractUI.cpp
index 07adce6..0f0960c 120000
--- a/plugins/dragonfly-room-reverb/AbstractUI.cpp
+++ b/plugins/dragonfly-room-reverb/AbstractUI.cpp
@@ -1 +1 @@
-../../common/AbstractUI.cpp
\ No newline at end of file
+#include "../../common/AbstractUI.cpp"
\ No newline at end of file
diff --git a/plugins/dragonfly-room-reverb/AbstractUI.hpp b/plugins/dragonfly-room-reverb/AbstractUI.hpp
index 39ad25a..806e283 120000
--- a/plugins/dragonfly-room-reverb/AbstractUI.hpp
+++ b/plugins/dragonfly-room-reverb/AbstractUI.hpp
@@ -1 +1 @@
-../../common/AbstractUI.hpp
\ No newline at end of file
+#include "../../common/AbstractUI.hpp"
\ No newline at end of file

```

**Pull request merged**
